<?php

/**
 * @file
 * Contains commerce_product_discount.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_product_discount_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_product_discount module.
    case 'help.page.commerce_product_discount':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables to provide per product discount and show discounted price, savings.') . '</p>';
      return $output;

    default:
  }
}
